spring:
  data:
    redis:
      host: ilovepc.duckdns.org
      port: 26379

# HS512 ????? ?? 64byte ??? secret key (??)
jwt:
  secret: 'aYourVeryLongAndComplexSecretKeyForHS512AlgorithmMustBeAtLeast64Bytes'
  access-token-validity: 3600000 # 1?? (ms)
  refresh-token-validity: 604800000 # 7? (ms)

#?? ????
resilience4j:
  circuitbreaker:
    configs:
      default: # ?? ??
        register-health-indicator: true
        sliding-window-type: COUNT_BASED # ?? ???? ??? ??
        sliding-window-size: 10          # ?? 10?? ??? ????
        failure-rate-threshold: 50       # 50% (?, 5?) ?? ????
        minimum-number-of-calls: 5       # (?? 5? ??? ??? ?? ??)
        wait-duration-in-open-state: 60s # ??? 60?? OPEN ??? ?? (3??? ??)

    instances:
       redis-set: # ? ??? ???? ??? ????.
         base-config: default # ? 'default' ??? ??


server:
  port: 9495