spring:
  data:
    redis:
      host: ilovepc.duckdns.org
      port: 26379


jwt:
  secret: 'YVlvdXJWZXJ5TG9uZ0FuZENvbXBsZXhTZWNyZXRLZXlGb3JIUzUxMkFsZ29yaXRobU11c3RCZUF0TGVhc3Q2NEJ5dGVz'
  access-token-validity: 3600000 # 1?? (ms)
  refresh-token-validity: 604800000 # 7? (ms)

rdb:
  master:
    jdbcUrl: jdbc:log4jdbc:mysql://ilovepc.duckdns.org:23306
    username: 'ENC(qRj4igOru2fvSCXeo/ncpw==)'
    password: 'ENC(UQNhMbgcTtv2ryTRjTSV2iPjAX2eo6wo)'
mybatis:
  mapper-locations: classpath:mapper/*.xml

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 60s

    instances:
       redis-set:
         base-config: default


server:
  port: 9495